### ISSUE TITLE
Error 400 bad request

### ISSUE THREAD

**Issue by omxeliw** [kipwoker/SoundCloud.API.Client#7]
Hi there!

Error 400 bad request 
   at System.Net.HttpWebRequest.GetResponse()
   at SoundCloud.API.Client.Internal.Infrastructure.Network.WebGateway.GetResponse(WebRequest request, Func`3 buildExceptionMessage) in C:\Users\WilsonMoreno\Downloads\ConsoleApp1\ConsoleApp1\SoundCloud.API.Client\Internal\Infrastructure\Network\WebGateway.cs:line 156

Headers: {Content-Type: application/jsonContent-Length: 0Accept-Encoding: gzip, deflate}

address: 
https://api.soundcloud.com/oauth2/token?client_id=CLIENT_ID&client_secret=CLIENTE_SECRET&grant_type=password&username=USERNAME&password=PASSWORD

First of all, I'm checking using postman and it's working
Credentials and AccessToken are OK

SoundCloud.API.Client Version 1.0.0.5

**Comment by mediaexplorer74** [comment]
> Credentials and AccessToken

Hi. How are you? Where do you get Credentials and AccessToken? I cannot register new app at SoundCloud dev page =(
Please share right client_id and client_secret if you can...
Best,
MediaExplorer
